### PR TITLE
Add build workflow

### PR DESCRIPTION
**Pull request by miguelaferreira**
This PR wants to add build automation to the project, it is work in progress. 

My idea was to open the PR to the forked repository first to test the build workflow. Here: https://github.com/miguelaferreira/ecsim/pull/1

Once that's working on the fork I'll update this PR.

### CODE REVIEW

**Comment by Limhes** [comment]
Thanks for setting up the build workflow!

The pyecsim binaries that you can find on [PyPI](https://pypi.org/project/pyecsim/) were built in the `quay.io/pypa/manylinux2014_x86_64` docker using auditwheel, running the following build script in the repository's `python` folder:

```
#!/bin/bash

# Install a system package required by our library
yum install -y eigen3

# Compile wheels
for PYBIN in /opt/python/*/bin; do
    "${PYBIN}/python" setup.py bdist_wheel
done

# Bundle external shared libraries into the wheels
for whl in dist/*.whl; do
    auditwheel repair "$whl"
done
```

**Comment by miguelaferreira** [comment]
Thanks for the instructions! 

I've added a `Dockerfile` that implements the build. Then I've also added a new workflow `release.yaml` to build the artefacts (using the Dockerfile) and create a github release with them. 

## Workflows
The build workflow (`.github/worflows/build.yaml`) runs on push to master and on any pull requests. What is does is run the python tests. 

The release workflow (`.github/worflows/release.yaml`) runs on git tags and it builds the python artefacts and then creates a github release with the artefacts. The tags still need to be manually created and pushed to github.

**Comment by miguelaferreira** [comment]
Latest build workflow I ran on my fork passed all tests 👍  https://github.com/miguelaferreira/ecsim/runs/2055062662?check_suite_focus=true

I'll test the release workflow as well, before making this PR final.

**Comment by miguelaferreira** [comment]
I've tested the release workflow and that seems to work too, see here https://github.com/miguelaferreira/ecsim/releases/tag/0.2.3.post2

When releasing we create a change log based on the commits since the last release. For that to work the repository must already have at least one release. I think it would make sense to create a git tag and corresponding release with the artefacts that are now on PyPI. Then once this PR is merged and a new tag is created the release workflow should work. 

Next I'm going to make sure that the python artefacts are included in the release and how to also upload them to PyPI as part of the release workflow.

**Comment by miguelaferreira** [comment]
@Limhes I got a release working on my fork and it already includes the linux binaries (see [here](https://github.com/miguelaferreira/ecsim/releases/tag/0.2.3.post2)).

Do you have any instructions for how to build the windows packages?

**Comment by Limhes** [comment]
That's great, nice work!

Building on Windows was done using MSVC 14.26.28801. After installing all the Python versions, the same scripts were called:

```
chcp 1250
"(...)\Python35\python" setup.py bdist_wheel
"(...)\Python36\python" setup.py bdist_wheel
"(...)\Python37\python" setup.py bdist_wheel
"(...)\Python38\python" setup.py bdist_wheel
"(...)\Python39\python" setup.py bdist_wheel
```

There were differences in the build between Python 3.9 and the versions before that. In Py<=3.8 I could use `m.attr("__version__") = VERSION_INFO;` (in pyecsim.cpp at the end), whereas for Py==3.9 I had to hard code the version number. No clue where that issue originated and if it is resolved by now. I'd have to look into that.

Do you have access to a Windows environment? I have a real machine and a virtual env here that I can test on.

**Comment by miguelaferreira** [comment]
Great, thanks! 

The procedure wold
1. Install the different python versions 
2. run the build for each version 

> whereas for Py==3.9 I had to hard code the version number.
Having to patch code during build will be hard so if you could find a way to not need is, that would be awesome.

I might also spin up a windows VM to test, or otherwise I'll just use GitHub Actions runtime to test.
I'll let you know if I face any issues.

**Comment by miguelaferreira** [comment]
@Limhes I've managed to get the windows builds also running in a workflow that splits jobs between Linux (all versions) and and several Windows jobs (one per version). Then a final job collects the artifacts in a single GitHub release. 

See here for the release workflow diagram: https://github.com/miguelaferreira/ecsim/actions/runs/649194917
And here for the resulting release with the artifacts: https://github.com/miguelaferreira/ecsim/releases/tag/0.2.3.post2

I did not include Python 3.9 on Windows since you said that the code needed patching. Patching the code in CI is a bad idea so I guess some additional logic needs to be added to the python build to make it work. Speaking of which, I did change the `setup.py` a bit to make sure cmake was picking up the eigen headers.

I'm happy with the PR so I will make it final.

One last remark, before the release workflow can make an actual release your repository need to have an initial release created manually. It's fine to just create an empty release manually just to make it work. However you could also create an initial release with the binaries that are already in PyPi. Just an idea.

**Pull request merged**
